update:
  before_script:
    - pip3 install wheel
    - pip3 install -r requirements.txt
    - pip3 freeze
    - mkdir --parents plots
  script:
    - python3 covid.py --log --suffix example
    - python3 covid.py --country DE --suffix example
    - python3 covid.py --country DE --log --diff --suffix example
  artifacts:
    paths:
      - plots/covid-19-world-cases-log-example.svg
      - plots/covid-19-de-cases-example.svg
      - plots/covid-19-de-cases-log-diff-example.svg
    expire_in: 1w
  timeout: 30m