stages:
  - check
  - deploy

.template: &template
  tags:
    - gitlab-org
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - venv/
  before_script:
    - (test -x venv/bin/python3 && test -x venv/bin/pip3) || (apt-get update -qy && apt-get install -y python3-pip python3-venv && python3 -m venv venv)
    - venv/bin/pip3 install wheel
    - venv/bin/pip3 install -r requirements.txt
  timeout: 10m

check:
  <<: *template
  stage: check
  script:
    - venv/bin/yapf --style google --parallel --verbose --diff covid.py
    - venv/bin/pylint covid.py

deploy:
  <<: *template
  stage: deploy
  needs:
    - check
  script:
    - venv/bin/python3 covid.py --log --suffix example
    - venv/bin/python3 covid.py --country DE --suffix example
    - venv/bin/python3 covid.py --country DE --log --diff --suffix example
  artifacts:
    paths:
      - plots/covid-19-world-cases-log-example.svg
      - plots/covid-19-de-cases-example.svg
      - plots/covid-19-de-cases-log-diff-example.svg
    expire_in: 1w