update:
  before_script:
    - apt-get update -qy
    - apt-get install -y python3-venv
    - python3 -m venv venv
    - venv/bin/pip3 install wheel
    - venv/bin/pip3 install -r requirements.txt
    - venv/bin/pip3 freeze
    - mkdir --parents plots
  script:
    - venv/bin/python3 covid.py --log --suffix example
    - venv/bin/python3 covid.py --country DE --suffix example
    - venv/bin/python3 covid.py --country DE --log --diff --suffix example
  artifacts:
    paths:
      - plots/covid-19-world-cases-log-example.svg
      - plots/covid-19-de-cases-example.svg
      - plots/covid-19-de-cases-log-diff-example.svg
    expire_in: 1w
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - venv/
  timeout: 10m