#!/bin/bash

PYTHON_FILES=$(find . -name '*.py' -not -path "*/venv/*")

if [ $? -eq 0 ]; then
    yapf --diff --style google --parallel --verbose $PYTHON_FILES && pylint --jobs=0 $PYTHON_FILES
else
    exit 0
fi

exit $?
