#!/bin/bash

PYTHON_FILES=$(find . -name '*.py')

if [ $? -eq 0 ]; then
    yapf --diff --style google --parallel --verbose $PYTHON_FILES
else
    exit 0
fi

if [ $? -eq 0 ]; then
    pylint --jobs=0 $PYTHON_FILES
else
    exit 1
fi

exit $?
