#!/bin/bash

PYTHON_FILES=$(git diff --name-only --cached --diff-filter=AM | grep --color=never '.py$')

if [ $? -eq 0 ]; then
    yapf --in-place --style google --parallel --verbose $PYTHON_FILES && git add $PYTHON_FILES
else
    exit 0
fi

exit $?
