#!/bin/bash

git stash  || true

rm -f plots/covid-19-world-cases-log-example.svg
rm -f plots/covid-19-de-cases-example.svg
rm -f plots/covid-19-de-cases-log-diff-example.svg

git add --force plots/covid-19-world-cases-log-example.svg
git add --force plots/covid-19-de-cases-example.svg
git add --force plots/covid-19-de-cases-log-diff-example.svg

git commit -m "Delete examples"

./covid.py --log --suffix example
./covid.py --country DE --suffix example
./covid.py --country DE --log --diff --suffix example

git add --force plots/covid-19-world-cases-log-example.svg
git add --force plots/covid-19-de-cases-example.svg
git add --force plots/covid-19-de-cases-log-diff-example.svg

git commit -m "Update examples"

if [ $? -eq 0 ]; then
    git push
else
    exit 1
fi

if [ $? -eq 0 ]; then
    git stash pop || true
else
    exit 1
fi
